name: CIQ Py SDK Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Optional, allows manual triggering
  schedule:
    # Run every hour
    - cron: "0 * * * *"

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r examples/dev-requirements.txt

      - name: Run flake8 (lint)
        run: |
          echo "Running flake8..."
          flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src --count --exit-zero --max-complexity=20 --max-line-length=120 --statistics

      - name: Run black (format check)
        run: |
          echo "Checking black formatting..."
          black --check .

      - name: Run All Example Scripts
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          find examples -name "*.py" -exec python {} \;
          # python examples/core-sanity/rag.py
          # pytest tests/integration --maxfail=1 --disable-warnings -q
